### ISSUE TITLE
Automato name

### ISSUE THREAD

**Issue by bsideup** [davidjfelix-legacy/automato-logo-svg#1]
Hi @DavidJFelix 

I'm developing a big automation framework and really want to take "automato" name, it was in my mind for the previous 1 year and I was a bit upset when discovered that I can't use this name on github :( 

Can I kindly ask you to give this name to me? Thanks a lot!

**Comment by oleg-nenashev** [comment]
The repo seems to have no public repositories, so such handover may be doable

**Comment by DavidJFelix** [comment]
This group has a number of private repositories and I quite like the name, as it's the name of the company behind them. While I empathize with you encountering what you believe to be a "parked" group name, I also know that the group name won't directly impact your project name. Might I suggest the following group name:

[automato-framework](https://github.com/automato-framework) which could then have `automato` be a project under it. My project is not in the automation space and I do not believe there will be any confusion. 

Again, I'm sorry if this isn't the response you're looking for.

**Comment by bsideup** [comment]
@DavidJFelix well, I expected such response. No worries, if it's being used - I can't force you. Have a nice day!

**Comment by DavidJFelix** [comment]
@bsideup Hope you find a name that works!
